apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-inference-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: model-inference
  template:
    metadata:
      labels:
        app: model-inference
    spec:
      containers:
      - name: model-inference
        image: docker-image
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: model-inference-service
spec:
  selector:
    app: model-inference
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
